[build]
command = "yarn && yarn build && mv packages/components/dist packages/app/dist/storybook"
publish = "packages/app/dist"
functions = "packages/functions/dist"

[build.environment]
YARN_VERSION = "1.5.1"
